"""Contract source of truth.

FastAPI derives OpenAPI from these models; `scripts/gen-types.sh` derives
`frontend/src/lib/api/generated.ts` from that OpenAPI. The frontend never hand-writes
an API type.

Change discipline:
  - Adding a field or a new enum variant or a new event type: free, no announcement.
  - Renaming or removing anything: tell the other developer first. With two people
    moving in parallel this is the rule that prevents a lost afternoon.
"""

from .common import Ack, ErrorDetail, ErrorResponse, Page, Schema, Ts, utcnow
from .document import Citation, Document, DocumentSource, DocumentStatus, DocumentUpdate
from .events import (
    AgentStateChangedData,
    AgentStateChangedEvent,
    AnsweredData,
    AnsweredEvent,
    ClarificationAskedData,
    ClarificationAskedEvent,
    ClientMessage,
    DocumentStatusChangedEvent,
    ErrorData,
    ErrorEvent,
    InterjectionProposedEvent,
    InterjectionUpdatedEvent,
    LiveEvent,
    MeetingStateChangedData,
    MeetingStateChangedEvent,
    ParticipantJoinedData,
    ParticipantJoinedEvent,
    ParticipantLeftData,
    ParticipantLeftEvent,
    ParticipantSpeakingChangedData,
    ParticipantSpeakingChangedEvent,
    QuestionCapturedData,
    QuestionCapturedEvent,
    SnapshotData,
    SnapshotEvent,
    TranscriptFinalEvent,
    TranscriptPartialEvent,
    WakeDetectedData,
    WakeDetectedEvent,
)
from .integration import (
    Integration,
    IntegrationCapability,
    IntegrationProvider,
    IntegrationStatus,
)
from .interjection import (
    CHAT_ALERT_MAX_CHARS,
    AskRequest,
    Interjection,
    InterjectionApprove,
    InterjectionDismiss,
    InterjectionKind,
    InterjectionStatus,
    InterjectionTrigger,
)
from .meeting import (
    AgentState,
    CitedDocument,
    Fixture,
    HarnessStart,
    HarnessStop,
    Meeting,
    MeetingBundle,
    MeetingCreate,
    MeetingPlatform,
    MeetingSource,
    MeetingState,
    MeetingStats,
    MuteRequest,
    RosterEntry,
    SourceQuote,
)
from .person import Person, PersonCreate, PersonUpdate
from .settings import (
    Autonomy,
    InterjectionPolicy,
    PersonaProviderName,
    PersonaSettings,
    PersonaTone,
    Settings,
    SettingsUpdate,
    TriageProviderName,
    TriageSettings,
    VoiceProviderName,
    VoiceSettings,
)
from .transcript import TranscriptSegment

__all__ = [
    "Ack",
    "AgentState",
    "AgentStateChangedData",
    "AgentStateChangedEvent",
    "AnsweredData",
    "AnsweredEvent",
    "AskRequest",
    "Autonomy",
    "CHAT_ALERT_MAX_CHARS",
    "Citation",
    "CitedDocument",
    "ClarificationAskedData",
    "ClarificationAskedEvent",
    "ClientMessage",
    "Document",
    "DocumentSource",
    "DocumentStatus",
    "DocumentStatusChangedEvent",
    "DocumentUpdate",
    "ErrorData",
    "ErrorDetail",
    "ErrorEvent",
    "ErrorResponse",
    "Fixture",
    "HarnessStart",
    "HarnessStop",
    "Integration",
    "IntegrationCapability",
    "IntegrationProvider",
    "IntegrationStatus",
    "Interjection",
    "InterjectionApprove",
    "InterjectionDismiss",
    "InterjectionKind",
    "InterjectionPolicy",
    "InterjectionProposedEvent",
    "InterjectionStatus",
    "InterjectionTrigger",
    "InterjectionUpdatedEvent",
    "LiveEvent",
    "Meeting",
    "MeetingBundle",
    "MeetingCreate",
    "MeetingPlatform",
    "MeetingSource",
    "MeetingState",
    "MeetingStateChangedData",
    "MeetingStateChangedEvent",
    "MeetingStats",
    "MuteRequest",
    "Page",
    "ParticipantJoinedData",
    "ParticipantJoinedEvent",
    "ParticipantLeftData",
    "ParticipantLeftEvent",
    "ParticipantSpeakingChangedData",
    "ParticipantSpeakingChangedEvent",
    "Person",
    "PersonaProviderName",
    "PersonaSettings",
    "PersonaTone",
    "PersonCreate",
    "PersonUpdate",
    "QuestionCapturedData",
    "QuestionCapturedEvent",
    "RosterEntry",
    "Schema",
    "Settings",
    "SettingsUpdate",
    "SnapshotData",
    "SnapshotEvent",
    "SourceQuote",
    "TranscriptFinalEvent",
    "TranscriptPartialEvent",
    "TranscriptSegment",
    "TriageProviderName",
    "TriageSettings",
    "Ts",
    "utcnow",
    "VoiceProviderName",
    "VoiceSettings",
    "WakeDetectedData",
    "WakeDetectedEvent",
]
